version: "3.7"
services:
  gibbon-mail:
    image: gibbonlab/gibbon-mail:latest
    ports:
      - 5000:5000
    volumes:
      - ../mail-templates/:/templates/
    environment:
      SMTP_LABEL: 'Mailcatcher 1'
      SMTP_USERNAME: user
      SMTP_PASSWORD: password
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      SMTP2_LABEL: 'Mailcatcher 2'
      SMTP2_USERNAME: user
      SMTP2_PASSWORD: password
      SMTP2_HOST: mailcatcher2
      SMTP2_PORT: 1025

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1025:1025"
      - "8025:1080"

  mailcatcher2:
    image: schickling/mailcatcher:latest
    ports:
      - "1026:1025"
      - "8026:1080"